# Create a Docker compose file to start up all 
# the previous containers. This Docker Compose 
# file will start the following systems:

# - TortoiseBot Gazebo simulation
# - Mapping nodes
# - Waypoints Action Server
# - Tortoisebot Webapp

version: '3.7'
services:
    roscore_server:
        hostname: roscore
        image: osrf/ros:noetic-desktop-full
        command: roscore
        networks:
            - ros-net

    gazebo_server:
        hostname: gazebo
        build:
            context: .
            dockerfile: tortoisebot-ros1-gazebo
        environment:
            - ROS_MASTER_URI=http://roscore_server:11311
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            - ros-net
        command: /bin/bash -c "sleep 2 && source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && roslaunch tortoisebot_gazebo tortoisebot_playground.launch"

    slam_server:
        hostname: slam
        build:
            context: .
            dockerfile: tortoisebot-ros1-slam
        environment:
            - ROS_MASTER_URI=http://roscore_server:11311
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            - ros-net
        command: /bin/bash -c "sleep 2 && source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && roslaunch tortoisebot_slam mapping.launch"

    waypoints_server:
        hostname: waypoints
        build:
            context: .
            dockerfile: tortoisebot-ros1-waypoints
        environment:
            - ROS_MASTER_URI=http://roscore_server:11311
        networks:
            - ros-net
        command: /bin/bash -c "sleep 5 && source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && rosrun course_web_dev_ros tortoisebot_action_server.py"

    webapp_server:
        hostname: webapp
        build:
            context: .
            dockerfile: tortoisebot-ros1-webapp
        environment:
            - ROS_MASTER_URI=http://roscore_server:11311
            - SLOT_ROSBRIDGE_PORT=20001
        networks:
            - ros-net
        ports: # works in this way -> host:container
            - "9090:9090"
            - "20001:20001"
        command: /bin/bash -c "sleep 5 && source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && roslaunch course_web_dev_ros web.launch"
        restart: always

networks:
    ros-net: