# Create a Docker compose file to start up all the 
# previous containers. This Docker Compose file will 
# start the following systems:

# - starting all the real robot systems
# - starting the mapping system

version: '3.7'
services:
    roscore_server:
        hostname: roscore
        build:
            context: .
            dockerfile: tortoisebot-ros1-real
        container_name: roscore_ros1_container
        environment:
            - DISPLAY
            - ROS_MASTER_URI=http://192.168.18.122:11311
            - ROS_HOSTNAME=192.168.18.122
            - ROS_IP=192.168.18.122
        volumes:
            - /dev:/dev
            - /opt/vc:/opt/vc
        command: /bin/bash -c "source /opt/ros/noetic/setup.bash && roscore"
        network_mode: host
        # networks:
        #     - ros1-net-real

    bringup_ros1_server:
        hostname: bringup_ros1
        build:
            context: .
            dockerfile: tortoisebot-ros1-real
        container_name: bringup_ros1_container
        environment:
            - DISPLAY
            - ROS_MASTER_URI=http://192.168.18.122:11311
            - ROS_HOSTNAME=192.168.18.122
            - ROS_IP=192.168.18.122
        volumes:
            - /dev:/dev
            - /opt/vc:/opt/vc
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true
        tty: true
        network_mode: host
        # networks:
        #     - ros1-net-real
        command: /bin/bash -c "sleep 2 && source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && roslaunch tortoisebot_firmware bringup.launch"

    slam_ros1_server:
        hostname: slam_ros1
        build:
            context: .
            dockerfile: tortoisebot-ros1-real
        container_name: slam_ros1_container
        environment:
            - DISPLAY
            - ROS_MASTER_URI=http://192.168.18.122:11311
            - ROS_HOSTNAME=192.168.18.122
            - ROS_IP=192.168.18.122
        volumes:
            - /dev:/dev
            - /opt/vc:/opt/vc
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true
        tty: true
        command: /bin/bash -c "sleep 10 && source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && roslaunch tortoisebot_slam mapping.launch"        

# networks:
#     ros1-net-real: